-- V4: Create roles table and insert default roles (USER and ADMIN)

-- Roles Table
CREATE TABLE roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    
    INDEX idx_role_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default roles
-- IDs will be auto-generated by AUTO_INCREMENT
INSERT INTO roles (name, description) VALUES
    ('USER', 'Standard user with basic access'),
    ('ADMIN', 'Administrator with full system access')
ON DUPLICATE KEY UPDATE name = name;

